Fix search
RTUITLab/ITLab-Projects pull request #57
Opened 2022-02-23 13:06 UTC by 0B1t322

Now searching projects by name field going without special characters

2022-02-23 13:11 UTC, 0B1t322 commented
Только остался вопрос когда пользователь вводит в поиск данные мне из них тоже убирать специальные символы?
То есть если пользователь ввел vr-d на самом деле бек будет искать по vrd

2022-02-23 21:00 UTC, CAPCHIK commented
Да, искать всегда по очищенной строке, если вдруг всплывёт как проблема - решим

2022-02-24 13:13 UTC, Suput commented
> Да, искать всегда по очищенной строке, если вдруг всплывёт как проблема - решим

Сейчас как сделано? Можно сливать?

2022-02-24 13:24 UTC, CAPCHIK requested changes
Регулярка сама по себе не совсем корректная, плюс не уверен, в том что запрос от пользователя тоже очищается

2022-02-24 13:24 UTC, CAPCHIK commented on src/ITLab-Projects/service/repoimpl/utils/builder/mongo/builder.go
> +									Regex: "[0-9a-zA-Z]",
Так не пойдет, а русские названия? Лучше не использовать алфавит, а пользоваться \w \W \s \W ну и вместо цифр есть \d

2022-02-24 13:28 UTC, 0B1t322 commented on src/ITLab-Projects/service/repoimpl/utils/builder/mongo/builder.go
> +									Regex: "[0-9a-zA-Z]",
Понял допишу сегодня

2022-02-24 14:25 UTC, 0B1t322 commented on src/ITLab-Projects/service/repoimpl/utils/builder/mongo/builder.go
> +									Regex: "[0-9a-zA-Z]",
Так \W учитывает - и _ потому вопрос зачем они в регулярке?
Собственно подобный вопрос про пробелы
Если проект называется VR Duel
он же должен так же искать по vrd

2022-02-25 14:31 UTC, CAPCHIK commented on src/ITLab-Projects/service/repoimpl/utils/builder/mongo/builder.go
> +									Regex: "[0-9a-zA-Z]",
Хм хм хм
Хз, ну ок, можно просто добавить русский алфавит,  и не париться, да

2022-02-25 14:47 UTC, 0B1t322 commented on src/ITLab-Projects/service/repoimpl/utils/builder/mongo/builder.go
> +									Regex: "[0-9a-zA-Z]",
Добавил в последних коммитах

2022-02-28 07:08 UTC, CAPCHIK commented
1. по итогу оставляем \w? Вроде говорили про добавление алфавита просто
2. Конфликты порешать бы сначала

2022-02-28 10:12 UTC, 0B1t322 commented
> 1. по итогу оставляем \w? Вроде говорили про добавление алфавита просто
> 2. Конфликты порешать бы сначала

1. Да кажется написанный мною тест не совсем все покрывал, сейчас поправлю и перепишу его
2. Как раз и конфликты сейчас решу

2022-02-28 12:01 UTC, CAPCHIK approved these changes

2022-03-02 15:22 UTC, merged